# This workflow will run tests using node

name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: [opened, synchronize, reopened, edited]

env:
  NODE: 16

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "${{ env.NODE }}"
      - run: npm ci
      - run: npm test
